import type { Metadata } from "next";
import { Sniglet, Quicksand } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const sniglet = Sniglet({ weight: '400', subsets: ['latin'], variable: '--font-sniglet' });
const quicksand = Quicksand({ subsets: ['latin'], variable: '--font-quicksand' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sniglet.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
